version: '3'
services:
  zookeeper:
    container_name: zk
    image: zookeeper:latest
    ports:
    - 2181:2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
    - 9092:9092
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=${HOST_IP}:2181
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_IP}:9092
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1